version: '3.8'

services:
  intelligent-typesetting:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - MODEL_DEVICE=cpu
      - DEBUG=false
      - LOG_LEVEL=INFO
    command: ["python", "-m", "src.cli", "info"] 