# 应用配置
app:
  name: "智能排版系统"
  version: "1.0.0"
  description: "基于CKIP Transformers的中文智能排版工具"
  debug: false
  log_level: "INFO"

# 模型配置
model:
  # BERT模型配置
  bert:
    model_name: "bert-base-chinese"  # 或 "hfl/chinese-bert-wwm-ext"
    max_length: 512
    batch_size: 8
    device: "auto"  # "cpu", "cuda", "auto"
  
  # 模型缓存目录
  cache_dir: "./models"
  
  # 模型保存路径
  save_path: "./models/intelligent_typesetting_model"

  ckip:
    model_name: "bert-base"
    # 小屏幕设备配置 (ST7306: 300x400像素)
    small_screen:
      chars_per_line: 16    # 每行16个中文字符
      lines_per_page: 12    # 每页12行
      margin_pixels: 20     # 留白像素
      screen_width: 300     # 屏幕宽度
      screen_height: 400    # 屏幕高度
      font_size: 16         # 字体大小(像素)
    
    # 标准配置
    standard:
      chars_per_line: 35    # 每行35个中文字符
      lines_per_page: 18    # 每页18行

# 数据处理配置
data:
  # 输入输出目录
  input_dir: "./data/input"
  output_dir: "./data/output"
  
  # 数据格式
  supported_formats: ["txt", "json", "csv"]
  
  # 编码
  encoding: "utf-8"
  
  # 文件处理配置
  file_processing:
    max_file_size: "10MB"
    backup_original: true
    create_backup: true

# 训练配置（如果需要微调）
training:
  learning_rate: 2e-5
  num_epochs: 3
  warmup_steps: 500
  weight_decay: 0.01
  gradient_accumulation_steps: 1
  
  # 验证配置
  validation_split: 0.1
  eval_steps: 500
  
  # 保存配置
  save_steps: 1000
  save_total_limit: 3

# 推理配置
inference:
  # 批处理大小
  batch_size: 8
  
  # 是否使用GPU
  use_gpu: true
  
  # 推理超时时间（秒）
  timeout: 30

# 日志配置
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  file: "./logs/app.log"
  max_size: "10MB"
  rotation: "1 day"
  retention: "30 days"

# API配置（如果需要提供API服务）
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 30

# 性能配置
performance:
  max_workers: 4
  timeout: 300
  memory_limit: "2GB"
  cache_enabled: true
  cache_size: "100MB"

# 输出格式配置
output:
  default_format: "txt"  # txt, json
  include_metadata: true
  include_entities: true
  include_tokens: false  # 小屏幕设备建议关闭
  
  # 小屏幕优化
  small_screen_optimized:
    enable: true
    remove_extra_spaces: true
    simplify_punctuation: true
    max_line_length: 16
    page_breaks: true 