# 应用配置
app:
  name: "Intelligent Typesetting"
  version: "0.1.0"
  debug: false
  log_level: "INFO"

# 模型配置
model:
  # BERT模型配置
  bert:
    model_name: "bert-base-chinese"  # 或 "hfl/chinese-bert-wwm-ext"
    max_length: 512
    batch_size: 16
    device: "auto"  # "cpu", "cuda", "auto"
  
  # 模型缓存目录
  cache_dir: "./models"
  
  # 模型保存路径
  save_path: "./models/intelligent_typesetting_model"

# 数据处理配置
data:
  # 输入输出目录
  input_dir: "./data/input"
  output_dir: "./data/output"
  
  # 数据格式
  supported_formats: ["txt", "json", "csv"]
  
  # 编码
  encoding: "utf-8"

# 训练配置（如果需要微调）
training:
  learning_rate: 2e-5
  num_epochs: 3
  warmup_steps: 500
  weight_decay: 0.01
  gradient_accumulation_steps: 1
  
  # 验证配置
  validation_split: 0.1
  eval_steps: 500
  
  # 保存配置
  save_steps: 1000
  save_total_limit: 3

# 推理配置
inference:
  # 批处理大小
  batch_size: 8
  
  # 是否使用GPU
  use_gpu: true
  
  # 推理超时时间（秒）
  timeout: 30

# 日志配置
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  file: "./logs/app.log"
  rotation: "1 day"
  retention: "30 days"

# API配置（如果需要提供API服务）
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 30 